ArgumentNullException: ThrowIfNull inlining & Cleanup
This is a (minor) performance change available in .NET 6 to allow JIT inlining in some paths that couldn't be before, due to the presence of a `throw`.

Note: there are more places in bindings that could benefit, but I'm not sure what the customer dependency story on WebJobs.Script is and if we can readily add a `net6.0` TFM there - needs input.